### ISSUE TITLE
Importing uclassify

### ISSUE THREAD

**Issue by Sorooshi** [psibi/pyuClassify#6]
I am trying to import uclassify on Jupyter notebook as follows.

from uclassify import uclassify

Here is the error I received:

ModuleNotFoundError        
Traceback (most recent call last)
<ipython-input-19-b80526abc695> in <module>()
----> 1 from uclassify import uclassify

ModuleNotFoundError: No module named 'uclassify'

This happens while I can simply run that line of code outside of Jupyter notebook.

I don't know whether this information is necessary or not, but by the way:

Operating system: Ubuntu 18.04
System configuration: 

capabilities: smbios-2.7 dmi-2.7 vsyscall32
configuration: boot=normal chassis=desktop family=To be filled by O.E.M. sku=To be filled by O.E.M. uuid=00000000-0000-0000-0000-0CC47A1DFA76

  *-core
       description: Motherboard
       product: X9SRH-7F/7TF
       vendor: Supermicro

 *-cpu
          description: CPU
          product: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
          vendor: Intel Corp.
          physical id: 4
          bus info: cpu@0
          version: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
          slot: SOCKET 0
          size: 3641MHz
          capacity: 4GHz
          width: 64 bits
          clock: 100MHz

**Comment by psibi** [comment]
I'm not sure why this doesn't work in Jupyter notebook (but works in python shell). Probably try the workaround suggested here: https://stackoverflow.com/questions/33960051/unable-to-import-a-module-from-python-notebook-in-jupyter

I would be willing to accept a PR fixing this (or documenting things if you have to do things differently in Jupyter notebook). Thanks!
